Refactor code
wumpz/jhotdraw pull request #11
Opened 2021-04-05 17:17 UTC by kenza-hareb

hi, i'm student, i made some modifications on your code as part of my software engineering project

2021-04-11 11:37 UTC, kenz-hr commented
Refactor code

2021-04-22 09:24 UTC, wumpz requested changes

2021-04-22 09:24 UTC, wumpz commented on jhotdraw-samples/jhotdraw-samples-misc/src/main/java/org/jhotdraw/samples/net/NetApplet.java
> +
Why is this replaced?

2021-04-22 09:24 UTC, wumpz commented on jhotdraw-samples/jhotdraw-samples-misc/src/main/java/org/jhotdraw/samples/net/NetPanel.java
> +        JRadioButtonMenuItem rbmi2 = new JRadioButtonMenuItem(new ZoomAction(editor, 0.25, null));
Why those variables? (rbmi3)

2021-04-22 09:24 UTC, wumpz commented on jhotdraw-samples/jhotdraw-samples-misc/src/main/java/org/jhotdraw/samples/odg/ODGApplicationModel.java
> +        ResourceBundleUtil LABELs = ResourceBundleUtil.getBundle(LABEL);
When renaming to a constant, then complete uppercase.

2021-04-22 09:24 UTC, wumpz commented on jhotdraw-samples/jhotdraw-samples-misc/src/main/java/org/jhotdraw/samples/odg/ODGApplicationModel.java
> +        drawLABELs.configureAction(aa, "view.toggleGrid");
strange naming

2021-04-22 09:24 UTC, wumpz commented on jhotdraw-samples/jhotdraw-samples-misc/src/main/java/org/jhotdraw/samples/svg/SVGView.java
> +    // Variables declaration - do not modify//GEN-BEGIN:variables
Why all those `// Variables declaration - do not modify//GEN-BEGIN:variables`? Where does this come from?

2023-02-02 12:25 UTC, closed without merging